### ISSUE TITLE
MQTT Collector kann keine Integer in ein Float Feld inserten

### ISSUE THREAD

**Issue by AlpenFlizzer** [solectrus/mqtt-collector#172]
Ich bekomme folgenden Fehler in den Logs des MQTT Collector Containers:

```
Subscribing to 4 topics:
- evcc/loadpoints/1/chargePower => PV:wallbox_charge_power (float)
- evcc/site/gridPower           => PV:grid_power_plus (+) PV:grid_power_minus (-) (float)
- evcc/site/homePower           => PV:house_power (float)
- evcc/site/pvPower             => PV:inverter_power (float)

# Message from 2024-06-02 15:56:26 +0000
  topic = evcc/loadpoints/1/chargePower
  message = 0
  => PV:wallbox_charge_power = 0.0
# Message from 2024-06-02 15:56:26 +0000
  topic = evcc/site/gridPower
  message = -872
  => PV:grid_power_minus = 872.0
  => PV:grid_power_plus = 0
Error while pushing to InfluxDB: failure writing points to database: partial write: field type conflict: input field "grid_power_plus" on measurement "PV" is type integer, already exists as type float dropped=1
```

Ich habe heute das env file an die neuen Gegebenheiten angepasst und die Influx, sowie MQTT Sensor/Topic Mappings angepasst.

Da mein Smart Meter prinzipiell Float anliefern kann, sind die MQTT Mappings als float definiert -> wird auch alles übernommen.
Aber wenn wenn es keine Nachkommastellen gibt, liefert der Smart Meter eine Ganzzahl. Hier hakt es dann meiner Meinung nach in der FluxWriter Klasse.

Müsste in https://github.com/solectrus/mqtt-collector/blob/develop/lib/flux_writer.rb
```
  def points(records, time:)
    records.map do |record|
      InfluxDB2::Point.new(
        time:,
        name: record[:measurement],
        fields: {
          record[:field] => record[:value],
        },
      )
    end
  end
```
nicht explizit eine Typkonversion basierend auf der Config machen, damit so ein Fehler nicht passiert?

EDIT: Jetzt wo ich den Fehlertext nochmal durchschaue, fällt mir auf, dass es immer `grid_power_minus` und `_plus`, welche synthetisch erzeugt werden. Also wird der Fehler eher dadurch behoben, dass man bei der Ableitung der Werte für diese Felder auf den Datentypen aus der Konfig Rücksicht nimmt?

https://github.com/solectrus/mqtt-collector/blob/develop/lib/mapper.rb
```
  def map_with_sign(mapping, value)
    [
      {
        measurement: mapping[:measurement_negative],
        field: mapping[:field_negative],
        value: value.negative? ? value.abs : 0, #gewagt, da man die Variablen auch als float definieren kann
      },
      {
        measurement: mapping[:measurement_positive],
        field: mapping[:field_positive],
        value: value.positive? ? value : 0,
      },
    ]
  end
```

**Comment by AlpenFlizzer** [comment]
#173

**Comment by ledermann** [comment]
Sehr gut erkannt, das hatte ich übersehen. Vielen Dank für deine Arbeit, ich bin begeistert! 👍

**Comment by AlpenFlizzer** [comment]
Sehr gerne - sehr langsam beginne ich Ruby und Solectrus zu verstehen ;-) 
Darf ich an der Stelle eine Release für den MQTT Collector anregen? 187 Commits auf Develop sprechen dafür. :-)

**Comment by ledermann** [comment]
Großartig, dass du dich da einarbeitest!

Ja, das letzte Release vom MQTT-Collector ist sehr lange her. Hintergrund ist die grundlegend überarbeitete Konfiguration mit den Sensoren. Der Code in `develop` ist quasi ein Rewrite. Dennoch möchte ich sicherstellen, dass das nächste Stable-Update abwärtskompatibel ist, dass bestehende User also nicht zwingend etwas ändern müssen.

Außerdem: Die `develop`-Varianten von Dashboard und MQTT-Collector bedingen sich gegenseitig. Daher möchte ich das nächste Release des MQTT-Collector synchron mit der anstehenden v0.15 des Dashboards rausbringen. Noch ein wenig Geduld...
