### ISSUE TITLE
Fehlende Werte, bzw. zusätzliche 0-Werte benötigt

### ISSUE THREAD

**Issue by bennysweb** [solectrus/mqtt-collector#221]
Ich habe eine OpenWB als Wallbox, welche die Ladewerte per MQTT ins Netzwerk pusht. Der MQTT-Collector sammelt diese auch zuverlässig ein und schreibt sie in die influxdb. Ich habe das Problem, dass mein Auto morgens etwas läd, dann ist es unterwegs und nachmittags läd es wieder. Der vormittags letzte gepushte Wert der Wallbox ist 0, der nächste in der Zeitreihe dann Nachmittags z.B. 4,5kW. Solectrus stellt dies leider als durchgängige Linie dar und auch die Berechnung des Ladetages stimmt somit nicht. Wenn ich manuell in der Datenbank zusätliche 0-Werte einfüge, stimmt sowohl die Grafik, als auch die Berechung des Ladetages. Kann man das irgendwie optimieren? Scheinbar schreibt der MQTT-Collector nur Werte, wenn sie sich ändern, oder?

<img width="1290" alt="Bildschirmfoto 2024-08-15 um 18 26 19" src="https://github.com/user-attachments/assets/48251e66-cd9c-4a30-896f-1641a5e1c672">
<img width="483" alt="Bildschirmfoto 2024-08-15 um 19 10 22" src="https://github.com/user-attachments/assets/091e7391-b408-451e-8d11-469dacc3cab5">

**Comment by bennysweb** [comment]
Bei der Ladestandsanzeige des Autos besteht das Problem ebenfalls. Der letzte Stand wird abgeholt und in Solectrus angezeigt. Nach einer Stunde ohne Änderung des Ladestandes (wenn der Verlauf in der Aktuell-Ansicht "weggelaufen" ist) kann dann der er nicht mehr angezeigt werden. In der Tagesansicht ist er noch vorhanden.

<img width="1261" alt="Bildschirmfoto 2024-08-15 um 22 31 59" src="https://github.com/user-attachments/assets/9148b00a-9039-43fe-b0fc-316c93868b4b">

<img width="1263" alt="Bildschirmfoto 2024-08-15 um 22 37 02" src="https://github.com/user-attachments/assets/6be58289-0121-4b0d-9124-08aa744ed9cf">

**Comment by ledermann** [comment]
Ja, bei lückenhaften Messwerten können Probleme entstehen:

- Diagramme können entartet aussehen, z.B. weil eine Kurve oberhalb der X-Achse beginnt oder endet (anstatt unten bei `0`)
- Energieberechnungen (kWh) werden ungenau, weil SOLECTRUS aus Performancegründen **nicht** das Integral berechnet, sondern die Summe der Stunden-Durchschnitte.

Es ist daher wichtig, dass Messwerte regelmäßig in InfluxDB landen. Auch, wenn sie sich nicht geändert haben oder `0` sind.

Der SENEC-Collector und der Shelly-Collector machen das sowieso, da tritt kein Problem auf. Beim MQTT-Colletor ist das etwas komplizierter. Hier bestimmt der MQTT-Broker, wie oft ein Messwert bereitgestellt wird. Beim ioBroker gibt es die Option "Publish only on Change", die man tunlichst **aus**schalten sollte. Andere MQTT-Broker haben eine solche Option möglicherweise gar nicht.

Der MQTT-Collector kann da wenig tun. Denkbar wäre, dass er, wenn innerhalb eines bestimmten Zeitfensters kein neuer Wert ankommt, den letzten bekannten erneut nach InfluxDB schreibt. Das wäre aber nur eine Notlösung.

Insofern erst mal die Frage an dich, @bennysweb, welchen MQTT-Broker du verwendest und ob es da nicht die Möglichkeit gibt, für regelmäßige Werte zu sorgen.

**Comment by bennysweb** [comment]
Die openWB ist der Broker und sendet alles quasi "von selbst" ins Netzwerk. Da kann man leider auch nichts zum Verhalten konfigurieren, zumindest habe ich nichts gefunden. Ich habe das jetzt anders gelöst und sende die Daten (SoC und Ladeleistung) per MQTT von HomeAssistant aus im 5 Sekunden Takt. Ich schließe das Issue, lag ja an meiner "kruden" Konfiguration.
