### ISSUE TITLE
Daten werden nicht angezeigt

### ISSUE THREAD

**Issue by ledermann** [solectrus/mqtt-collector#23]
Von @derheinrich2019:

> Das Dashboard hat mir sofort gefallen und möchte es gerne "sehen" :)
> 
> Meine Konfig: Solaredge --> evcc --> solectrus (mqtt-collector)
> 
> Ich bin die Anleitung soweit erfolgreich durchgegangen. Einziger Unterschied: Statt einem Pi hab ich eine Proxmox-VM mit arm eingesetzt. Läuft auch alles - es werden leider nicht die Daten aus evcc angezeigt.
> 
> Das Docker-Log zeigt mir an, dass die Abfrage der MQTT-Daten klappt:
> mqtt-collector-mqtt-collector-1  | 2023-05-24 11:07:01 +0000 {"house_power"=>801}
> mqtt-collector-mqtt-collector-1  | 2023-05-24 11:07:09 +0000 {"wallbox_charge_power"=>0}
> mqtt-collector-mqtt-collector-1  | 2023-05-24 11:07:09 +0000 {"inverter_power"=>6983}
> mqtt-collector-mqtt-collector-1  | 2023-05-24 11:07:09 +0000 {"bat_fuel_charge"=>77.0}
> 
> Wenn ich über den Influxdb-Admin die Daten anschaue, sind dort der Forecast und die PV-Daten vorhanden.
> 
> Im Dashboard kommen keine Daten an, nur in der Tagesansicht werden die Forecastdaten angezeigt. Daher würde ich vermuten, dass auch die Anbindung influxdb klappt.
> 
> Achja, im Docker-Compose-File hab ich den Container für Senec auskommentiert.
> 
> Vielleicht hat ja @ledermann eine Idee?
> 
> Besten Dank schonmal!
> 
_Originally posted by @derheinrich2019 in https://github.com/solectrus/solectrus/discussions/1620#discussioncomment-5988407_

**Comment by derheinrich2019** [comment]
Danke für dein schnelles Feedback!

Ja genau, in der InfluxDB kommen die Daten an - nur nicht im Dashboard (außer die Forecast-Daten).

Ich hab jetzt in beiden .env Dateien auf SENEC geändert. Aber dann ging noch weniger

mqtt-collector:
mqtt-collector-mqtt-collector-1  | Error while pushing to InfluxDB: Connection reset by peer
mqtt-collector-mqtt-collector-1  | Error while pushing to InfluxDB: bucket "SENEC" not found

Anbei die beiden .env Dateien.


[env_mqtt.txt](https://github.com/solectrus/mqtt-collector/files/11556901/env_mqtt.txt)

[env_solectrus.txt](https://github.com/solectrus/mqtt-collector/files/11556903/env_solectrus.txt)

**Comment by derheinrich2019** [comment]
Besten Dank! Jetzt funktioniert es! 
Problem war INFLUX_BUCKET und INFLUX_MEASUREMENT.

Nach den paar Stunden fällt mir auf, dass die Berechnung von Kosten und Einsparung nicht stimmen kann. Ich schaue mir das morgen nach einem kompletten Tag nochmal an.

**Comment by ledermann** [comment]
Das klingt schon mal gut.

Bezüglich Kosten: Derzeitig stellt SOLECTRUS kalkulatorische Kosten dar, das wird aber von vielen als irritierend empfunden und daher mit dem nächsten Update geändert:
https://github.com/solectrus/solectrus/issues/1891

Ansonsten: Zur korrekten Berechnung müssen Strompreis und Einspeisevergütung richtig eingestellt sein (Menü "Einstellungen"). Wichtig ist hier auch das richtige Gültigkeitsdatum.

**Comment by ledermann** [comment]
@derheinrich2019 Mich würde interessieren, ob sich die Darstellung von Kosten und Einsparung mittlerweile eingependelt hat. Oder gibt es da weiterhin Probleme?

**Comment by derheinrich2019** [comment]
Ich bin da einfach mit den falschen Erwartungen rangegangen.
Mich interessieren - auch der einfachen Übersicht halber - nur:
Kosten sind für mich die Kosten, die tatsächlich durch den Netzbezug entstehen. 
Vergütung, die aus dem reinen Stromverkauf entstehen.
Gespart durch den Eigenverbrauch. Also alles, was ich aus selbsterzeugten Strom (PV direkt oder dann aus dem Akku).

Ich finde die aktuelle Darstellung, den Vergleich zum Volleinspeiser etwas schwierig. Aber wenn man es mal verstanden hat, macht es durchaus Sinn ;)

Bin gespannt, wie es hier weitergeht. --> https://github.com/solectrus/solectrus/issues/1891

**Comment by ledermann** [comment]
@derheinrich2019 Prima, danke für die Rückmeldung. An der Darstellung der realen Kosten (anstelle der kalkulatorischen) sind wir ja gerade dran, das wird also mit dem nächsten Update klarer.

Freut mich, dass alle begeistert sind 😄 
Mit dem MQTT-Collector erweitert sich die Zielgruppe für SOLECTRUS erheblich, daher ist mir wichtig, etwaige Probleme damit schnell aus dem Weg zu räumen. Ich gehe nun davon aus, dass bei Dir die Messwerte korrekt in SOLECTRUS ankommen und schließe dieses Issue. Bei neuen Beobachtungen oder Problemen kannst Du gerne ein neues Issue aufmachen.
