### ISSUE TITLE
Probleme Benennung Sensorpfad (evtl. zu lang oder ungültige Zeichen?

### ISSUE THREAD

**Issue by StevieC121176** [solectrus/mqtt-collector#284]
Installation verlief bei mir erwartungsgemäß ohne Probleme. Einzig Dashboard heißt bei mir noch App und der MQTT Collector hat mit einem Sensorpfad Probleme (evtl. zu lang?). Ich hab den im ioBroker umbenannt, dann hat es funktioniert.

_Originally posted by @StevieC121176 in https://github.com/solectrus/solectrus/discussions/3749#discussioncomment-11492813_

Es handelt sich um diesen Pfad: `Solectrus/shelly/0/shellyplusplugs#e543b8b67342#1/Relay0/Power`
ich tippe mal auf den Hashtag `#`

**Comment by ledermann** [comment]
Ja, ein Hashtag (`#`), macht in einer `.env` Probleme, weil es als Kommentar-Trenner aufgefasst wird.

Eine solche Schreibweise funktioniert somit nicht:

```env
MAPPING_42_TOPIC=Solectrus/shelly/0/shellyplusplugs#e543b8b67342#1/Relay0/Power
```

In solchen Fällen muss die Angabe mit Anführungszeichen erfolgen, also so:

```env
MAPPING_42_TOPIC="Solectrus/shelly/0/shellyplusplugs#e543b8b67342#1/Relay0/Power"
```

Keine Änderung im MQTT-Collector erforderlich :)
