### ISSUE TITLE
Status-Anzeige wechselt willkürlich

### ISSUE THREAD

**Issue by ledermann** [solectrus/mqtt-collector#36]
_Originally posted by @StevieC121176 in https://github.com/solectrus/solectrus/issues/2132#issuecomment-1615695036_

> Ich persönlich schaue doch recht oft auf die Wetterdaten, deswegen lasse ich mir die auch in dieser Infozeile anzeigen (jetzt nur die Wetterdaten, keine Wechselrichterinfos mehr (die waren bei meinem Wechselrichter nicht sonderlich relevant)). Allerdings habe ich dabei ein kleines Problem. Die Anzeige wechselt ca. alle 5min von meinem Wetterdaten auf "Live". Nach 5min ca. werden dann wieder für ca. 5 min meine Wetterdaten angezeigt. Der Punkt daneben bleibt allerdings immer grün. Der Datenpunkt im iobroker ist auch immer gefüllt und wird per MQTT bereit gestellt. 
Hat jemand eine Ahnung woran das Wechseln der Anzeige liegen kann?
 
![IMG_1018](https://github.com/solectrus/solectrus/assets/113791299/06dd0c99-91ae-45c4-af8d-64da6d8a58e6)

**Comment by ledermann** [comment]
Möglicherweise wird das durch diesen Fix ebenfalls behoben:
https://github.com/solectrus/solectrus/issues/2238

Zum Ausprobieren und Testen steht das `development` Image zur Verfügung:
`ghcr.io/solectrus/solectrus:develop`

**Comment by StevieC121176** [comment]
Aus meiner Sicht könnte der Issue geschlossen werden. Oben genanntes Problem konnte ich nicht mehr beobachten, läuft bestens.
