### ISSUE TITLE
Absturz bei Restart dest MQTT Brokers

### ISSUE THREAD

**Issue by Robbe64** [solectrus/mqtt-collector#70]
Heute nacht hat sich mein MQTT-Broker (in Node-RED) mehrmals wegen eines Fehlers neugestartet.
Das war auch lange kein echtes Problem nur irgendwann ist die Verbindung wohl zu einem ungünstigen Zeitpunkt abgebrochen, so dass der collector sich beendet hat.
Leder hat auch docker nicht bemerken können, dass der collector nicht mehr läuft und somit wurde der container auch nicht automatisch neu gestartet.
Nach einem neustart heute morgen lief wieder alles normal.

Aus meiner sicht also 2 Probleme:
1. Der Absturz  des collectors selbst
2. Der Container erkennt nicht, dass er unhealthy ist.

[_solectrus1-mqtt-collector-1_logs.txt](https://github.com/solectrus/mqtt-collector/files/12865508/_solectrus1-mqtt-collector-1_logs.txt)

**Comment by ledermann** [comment]
Danke für den Hinweis. Mal sehen, wie ich den Collector robuster gegen Ausfälle des MQTT-Brokers absichern kann.

Dass der Container nicht automatisch neu gestartet wurde, verstehe ich aber nicht so recht. In der `docker-compose.yml` findet sich nämlich ein [restart: always](https://github.com/solectrus/hosting/blob/1d933b24c03324d40e9032f9d361ad6ea1177cba/guide/mqtt-iobroker/docker-compose.yml#L135), sodass genau dieser Neustart veranlasst werden sollte. Hast du das bei dir vielleicht manuell herausgenommen?

**Comment by ledermann** [comment]
Ok, verstehe. Grund ist wohl, dass es zwar ein Exception-Handling gibt und somit der Container weiterläuft, aber bei einer verlorenen Verbindung zum MQTT-Broker nicht erneut ein Subscribe durchgeführt wird. Genau das müsste aber passieren. Ich kümmere mich bei Gelegenheit darum :)

**Comment by andrebeekhuis** [comment]
Ich hatte gerade ein ähnliches Szenario. Nach Umbauarbeiten mit mehrfachem Neustart des mqtt brokers stand der mqtt-collector leider still. Das habe ich leider erst zwei Tage später bemerkt, so oft schaue ich nicht ins Solectrus Dashboard. Leider klafft in den Daten nun natürlich eine kräfitge Lücke! Eventuell macht ein health-check hier Sinn, ähnlich zu den anderen Containern?

**Comment by ledermann** [comment]
@andrebeekhuis Ja, der Hinweis auf den HealthCheck ist gut. Da muss ich mir mal überlegen, wie der stattfinden könnte. Vielleicht regelmäßig nach erfolgreichem InfluxDB-Write einen Timestamp in eine Datei schreiben, die dann Docker per HEALTHCHECK auswerten kann. Mal sehen.

**Comment by ledermann** [comment]
@andrebeekhuis Mir ist nicht ganz klar, was genau du mit "... stand der mqtt-collector leider still" meinst. Wenn der Container gar nicht läuft, bringt ja auch ein HealthCheck nichts. Ein HealthCheck ermöglicht nur eine differenzierte Sicht auf einen **laufenden** Container.

Wenn ich nun einen HealthCheck einbaue, dann würde der nur prüfen können, ob der Container weiterhin auf MQTT-Events lauscht, was zweifellos sinnvoll ist. Aber ob Daten hereinkommen und ob diese auch erfolgreich nach InfluxDB geschrieben werden können, liegt außerhalb der Verantwortung des mqtt-collectors.

**Comment by Robbe64** [comment]
Wann können wir denn mit einer aktualisierten Version rechnen? :)

**Comment by ledermann** [comment]
Eine größere Update-Welle ist in Arbeit. Wird hoffentlich nur noch wenige Tage dauern.

@Robbe64 Was du gerne tun kannst, ist ein Switch des MQTT-Collectors von `latest` auf `develop`. Die Konfiguration hat sich total geändert (siehe [Wiki](https://github.com/solectrus/mqtt-collector/wiki/Konfiguration)), aber es sollte abwärtskompatibel sein. Feedback wäre sehr hilfreich - bei Problemen oder Fragen aber besser neues Issue anlegen.
